version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  build:
    commands:
      - echo "Zipping Lambda function"
      - zip -r lambda.zip index.js package.json

artifacts:
  files:
    - lambda.zip
