version: 0.2
phases:
  pre_build:
    commands:
      - echo "Setting up locale..."
      - export LC_ALL="en_US.UTF-8" && locale-gen en_US.UTF-8
      - echo "Fetching current alias version..."
      - CURRENT_VERSION=$(aws lambda get-alias \
          --function-name my-lambda-function \
          --name live \
          --query 'FunctionVersion' \
          --output text)
      - echo "Publishing new Lambda version..."
      - TARGET_VERSION=$(aws lambda publish-version \
          --function-name my-lambda-function \
          --description "Automated deploy")
      - echo "Generating appspec.yml with versions $CURRENT_VERSION -> $TARGET_VERSION"
      - |
        cat > appspec.yml <<EOF
        version: 0.0
        Resources:
          - myLambdaFunction:
              Type: AWS::Lambda::Function
              Properties:
                Name: "my-lambda-function"
                Alias: "live"
                CurrentVersion: "$CURRENT_VERSION"
                TargetVersion: "$TARGET_VERSION"
        Hooks:
          - BeforeAllowTraffic: "ValidateBeforeTrafficShift"
          - AfterAllowTraffic:  "ValidateAfterTrafficShift"
        EOF
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Packaging Lambda function..."
      - zip -r function.zip index.js node_modules package.json
artifacts:
  files:
    - function.zip
    - appspec.yml
  discard-paths: yes
